#pragma once

#include "IExpression.h"
#include "Expressions/CIdExpression.h"
#include "Expressions/CBinaryExpression.h"
#include "Expressions/CNumberExpression.h"
#include "Expressions/CBinaryBooleanExpression.h"
#include "Expressions/CBooleanExpression.h"
#include "Expressions/CThisExpression.h"
#include "Expressions/CNewObjectExpression.h"
#include "Expressions/CNewIntArrayExpression.h"
#include "Expressions/CMethodCallExpression.h"
#include "Expressions/CArrayLengthExpression.h"
#include "Expressions/CArrayIndexExpression.h"
#include "Expressions/CCompoundExpression.h"